name: Copy, Zip, and Commit Source Files

on:
  push:
    branches:
      - main  # Adjust the branch as per your default branch name

jobs:
  copy_zip_and_commit:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out the repository content

      - name: Create Toolkit Directory
        run: mkdir -p PSMDSOCoptimization/PSMDSOCoptimization  # Create the target directory

      - name: Copy source files
        run: cp -r src/. PSMDSOCoptimization/PSMDSOCoptimization  # Copy all files from src folder to PSMDSOCoptimization

      - name: Zip Toolkit
        run: |
          cd PSMDSOCoptimization
          zip -r ../SentinelTIUploadToolkit.zip ./*

      - name: Move Artifact to Module Folder
        run: mv PSMDSOCoptimization.zip Module/

      - name: Commit new zip file
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add Module/PSMDSOCoptimization.zip
          git commit -m "Update PSMDSOCoptimization.zip"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
